<?php
/**
 * @package Vine-House-Farm.
 * @author: A.A.Treitjak <a.treitjak@gmail.com>
 * @copyright: 2012 - 2015 BelVG.com
 */

class Vinehousefarm_Birdlibrary_Model_Bird extends Mage_Core_Model_Abstract
{
    public function _construct()
    {
        parent::_construct();
        $this->_init('birdlibrary/bird');
    }

    protected function _beforeSave()
    {
        if ($this->hasData('in_products') && !is_array($this->getInProducts())) {
            $products = array();
            parse_str($this->getInProducts(), $products);
            $this->setInProducts($products);
        }

        if ($this->hasData('in_links') && !is_array($this->getInLinks())) {
            $links = array();
            parse_str($this->getInLinks(), $links);
            $this->setInLinks($links);
        }

        if ($this->hasData('gallery') && !is_array($this->getGallery())) {
            $images = Mage::helper('core')->jsonDecode($this->getGallery());
            $this->setGallery($images);
        }

        return parent::_beforeSave(); // TODO: Change the autogenerated stub
    }

    protected function _afterSave()
    {
        if ($this->getInProducts()) {

            /**
             * @var $delete Vinehousefarm_Birdlibrary_Model_Resource_Product_Collection
             */
            $delete = Mage::getModel('birdlibrary/product')->getCollection()
                ->addFieldToFilter('bird_id', $this->getId());

            $delete->walk('delete');

            /**
             * @var $create Vinehousefarm_Birdlibrary_Model_Resource_Product_Collection
             */

            $create = Mage::getModel('birdlibrary/product')->getCollection();

            foreach ($this->getInProducts() as $productId) {

                /**
                 * @var $linkModel Vinehousefarm_Birdlibrary_Model_Product
                 */

                $linkModel = Mage::getModel('birdlibrary/product');
                $linkModel->isObjectNew(true);
                $linkModel->setBirdId($this->getId());
                $linkModel->setProductId($productId);
                $linkModel->save();

                //$create->addItem($linkModel);
            }

            //$create->walk('save');
        }

        if ($this->getInLinks()) {

            /**
             * @var $delete Vinehousefarm_Birdlibrary_Model_Resource_Link_Collection
             */
            $delete = Mage::getModel('birdlibrary/link')->getCollection()
                ->addFieldToFilter('bird_id', $this->getId());

            $delete->walk('delete');

            /**
             * @var $create Vinehousefarm_Birdlibrary_Model_Resource_Link_Collection
             */

            $create = Mage::getModel('birdlibrary/link')->getCollection();

            foreach ($this->getInLinks() as $linkId) {

                /**
                 * @var $linkModel Vinehousefarm_Birdlibrary_Model_Product
                 */

                $linkModel = Mage::getModel('birdlibrary/link');
                $linkModel->isObjectNew(true);
                $linkModel->setBirdId($this->getId());
                $linkModel->setLinkId($linkId);
                $linkModel->save();;

                //$create->addItem($linkModel);
            }

            //$create->walk('save');
        }

        if ($this->getGallery()) {
            /**
             * @var $delete Vinehousefarm_Birdlibrary_Model_Resource_Gallery_Collection
             */
            $delete = Mage::getModel('birdlibrary/gallery')->getCollection()
                ->addFieldToFilter('bird_id', $this->getId());

            $delete->walk('delete');

            /**
             * @var $create Vinehousefarm_Birdlibrary_Model_Resource_Gallery_Collection
             */

            $create = Mage::getModel('birdlibrary/gallery')->getCollection();

            foreach ($this->getGallery() as $image) {

                $file = str_replace('.tmp', '', $image['file']);

                /**
                 * @var $linkModel Vinehousefarm_Birdlibrary_Model_Gallery
                 */
                if ($image['removed']) {
                    unlink(Mage::getSingleton('birdlibrary/product_media_config')->getMediaPath($file));
                    continue;
                }

                $imageModel = Mage::getModel('birdlibrary/gallery');
                $imageModel->isObjectNew(true);
                $imageModel->setData($image);
                $imageModel->setBirdId($this->getId());
                $imageModel->setUrl($file);
                $imageModel->setFile($file);
                $imageModel->save();

                //$create->addItem($imageModel);
            }

            //$create->walk('save');
        }

        return parent::_afterSave(); // TODO: Change the autogenerated stub
    }

    protected function _afterDelete()
    {
        if ($this->getInProducts()) {

            /**
             * @var $delete Vinehousefarm_Birdlibrary_Model_Resource_Product_Collection
             */
            $delete = Mage::getModel('birdlibrary/product')->getCollection()
                ->addFieldToFilter('bird_id', $this->getId());

            $delete->walk('delete');
        }

        if ($this->getInLinks()) {

            /**
             * @var $delete Vinehousefarm_Birdlibrary_Model_Resource_Link_Collection
             */
            $delete = Mage::getModel('birdlibrary/link')->getCollection()
                ->addFieldToFilter('bird_id', $this->getId());

            $delete->walk('delete');
        }

        if ($this->getGallery()) {
            /**
             * @var $delete Vinehousefarm_Birdlibrary_Model_Resource_Gallery_Collection
             */
            $delete = Mage::getModel('birdlibrary/gallery')->getCollection()
                ->addFieldToFilter('bird_id', $this->getId());

            $delete->walk('delete');
        }

        return parent::_afterDelete(); // TODO: Change the autogenerated stub
    }

    protected function _afterLoad()
    {
        if (!$this->getInProducts()) {

            /**
             * @var $products Vinehousefarm_Birdlibrary_Model_Resource_Product_Collection
             */
            $products = Mage::getModel('birdlibrary/product')->getCollection()
                ->addFieldToFilter('bird_id', $this->getId());

            $result = array();

            foreach ($products as $product) {
                $result[] = $product->getProductId();
            }

            if ($result) {
                $this->setInProducts($result);
            } else {
                $this->setInProducts('');
            }
        }

        if (!$this->getInLinks()) {

            /**
             * @var $links Vinehousefarm_Birdlibrary_Model_Resource_Link_Collection
             */
            $links = Mage::getModel('birdlibrary/link')->getCollection()
                ->addFieldToFilter('bird_id', $this->getId());

            $result = array();

            foreach ($links as $link) {
                $result[] = $link->getLinkId();
            }

            if ($result) {
                $this->setInLinks($result);
            } else {
                $this->setInLinks('');
            }
        }

        if (!$this->getGallery()) {

            $images = array();

            /**
             * @var $collection Vinehousefarm_Birdlibrary_Model_Resource_Gallery_Collection
             */
            $collection = Mage::getModel('birdlibrary/gallery')->getCollection()
                ->addFieldToFilter('bird_id', $this->getId());

            foreach ($collection as $image) {

                if ($image['disabled']) {
                    continue;
                }

                /**
                 * @var $image Vinehousefarm_Birdlibrary_Model_Gallery
                 */
                $imageData['label'] = (string) $image->getLabel();
                $imageData['label_default'] = (string) $image->getLabel();
                $imageData['url'] = Mage::getSingleton('birdlibrary/product_media_config')->getMediaUrl($image->getFile());
                $imageData['file'] = (string) $image->getFile();
                $imageData['position'] = (int) $image->getPosition();
                $imageData['position_default'] = (int) $image->getPosition();
                $imageData['disabled'] = (int) $image->getDisable();
                $imageData['disabled_default'] = (int) $image->getDisable();
                $imageData['product_id'] = (int) $image->getBirdId();
                $imageData['value_id'] = (int) $image->getId();

                $images[] =  $imageData;
            }

            $this->setGallery($images);
        }

        return parent::_afterLoad(); // TODO: Change the autogenerated stub
    }
}