
<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php if($this->canShowBlock()): ?>
<div class="block block-layered-nav side-nav-categories whf-filters">
    <div class="block-title">
        <?php // echo $this->__('Shop By') ?>
        <?php echo $this->__('Filter') ?>
    </div>
    <div class="block-content box-content box-category">
        <?php echo $this->getStateHtml() ?>
        <?php if ($this->getLayer()->getState()->getFilters()): ?>
            <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
        <?php endif; ?>
        <?php if($this->canShowOptions()): ?>
            <?php /*<p class="block-subtitle"><?php echo $this->__('Shopping Options') ?></p>*/ ?>
            <?php /*<dl id="narrow-by-list">*/ ?>
            <ul>
                <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): ?>
                <?php if($_filter->getItemsCount()): ?>
                    <li>
                        <span class="whf-a"><?php echo $this->__($_filter->getName()) ?></span>
                        <span class="subDropdown plus"></span>
                        <?php echo $_filter->getHtml() ?>
                    </li>
                <?php endif; ?>
                <?php endforeach; ?>
            </ul>
            <?php /*</dl>*/ ?>
            <script type="text/javascript">decorateDataList('narrow-by-list')</script>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
