<?php /*
	<?php
		$category = Mage::getSingleton('catalog/layer')->getCurrentCategory();
		$categories = $category->getCollection()
			->addAttributeToSelect(array('name', 'thumbnail', 'description', 'image'))
			->addAttributeToFilter('is_active', 1)
			->addIdFilter($category->getChildren())
	?>
	<div class="whf-subcategories">
		<ul>

		<?php foreach ($categories as $category): ?>
		<li class="whf-subcategory">
			<div class="whf-subcategory-thumb">
				<img src="<?php echo $category->getImageUrl() ?>" />
			</div>
			<div class="whf-subcategory-description">
				<h3 class="whf-subcategory-name"><?php echo $category->getName() ?></h3>
				<p><?php echo $category->getDescription() ?></p>
				<a class="whf-button" href="<?php echo $category->getUrl() ?>">products</a>
			</div>
		</li>
		<?php endforeach; ?>

		</ul>
	</div>

	<?php // echo $this->getLayout()->createBlock('cms/block')->setBlockId('subcategory-bird')->toHtml() ?>
*/ ?>
