<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $posts = $this->getPosts() ?>
<?php $helper = Mage::helper('vinehousefarm_common'); ?>
<?php if (count($posts) > 0): ?>
	<div class="blog_post">
		<?php if ($title = $this->getTitle()): ?>
			<div class="new_title center whf-blog-title">
				<h2><?php echo $this->__($title) ?></h2>
			</div>
		<?php endif; ?>
		<div class="block-content">
			<ul style="top: 0px; left: 0px;">
			<?php foreach($posts as $post): ?>
				<li>
					<?php if (($featuredImage = $post->getFeaturedImage())) { ?>
						<div class="blog-l blog-img">
							<a href="<?php echo $post->getPermalink() ?>">
								<img src="<?php echo $featuredImage->getAvailableImage() ?>" width="300" height="200" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>" />
							</a>
						</div>
					<?php } ?>
					<h2><a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->htmlEscape($post->getPostTitle()) ?>"><?php echo $this->htmlEscape($post->getPostTitle()) ?></a></h2>
					<div class="whf-details">
<ul class="whf-blog-social">
<li class="whf-blog-social-profile whf-fb" style="height: 40px;"><a href="http://www.facebook.com/sharer.php?u=<?php echo $post->getPermalink() ?>" target="_blank"></a></li>
<li class="whf-blog-social-profile whf-tw" style="height: 40px;"><a href="http://twitter.com/share?url=<?php echo $post->getPermalink() ?>" target="_blank"></a></li>
<li class="whf-blog-social-profile whf-gp" style="height: 40px;"><a href="https://plus.google.com/share?url=<?php echo $post->getPermalink() ?>" target="_blank"></a></li>
</ul>
						<h3>
							<time class="entry-date" datetime="<?php echo date('c', strtotime($post->getPostDate()));?>"><?php echo date('F d, Y', strtotime($post->getPostDate()));?></time>
						</h3>
						<?php $category = $helper->getPostCategory($post); ?>
						<?php if ($category): ?>
							<h4>Category: <a href="<?php echo $category->getUrl() ?>"><?php echo $category->getName() ?></a></h4>
						<?php endif ?>
					</div>
				</li>
			<?php endforeach; ?>
			</ul>
		</div>
	</div>
<?php endif; ?>
