<?php
/**
 * @package Vine-House-Farm.
 * @author: A.A.Treitjak <a.treitjak@gmail.com>
 * @copyright: 2012 - 2015 BelVG.com
 */
?>
<?php if ($this->getOrder()->getId()): ?>
<div>
    <form action="#" id="authoriselist" name="authoriselist" method="post">
        <input name="orderid" type="hidden" value="<?php echo $this->getOrder()->getId() ?>"/>
        <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>" />
    <table width="100%" cellspacing="0">
        <tr>
            <td width="40%"><h1><?php echo $this->__('Order:') ?> <?php echo $this->getOrder()->getRealOrderId() ?></h1></td>
            <td width="25%">
                <table width="100%" cellspacing="0">
                    <tr>
                        <td><h3><?php echo $this->__('Dispatch Date:') ?></h3></td>
                        <td style="padding-right: 10px;">
                            <input name="shipping_arrival_date_display" id="shipping_arrival_date_display" value="<?php echo $this->getShippingArrivalDate() ?>" title="date" class="input-text required-entry" style="width: 100px;" type="text"> <img style="display: initial;" src="<?php echo Mage::getBaseUrl('skin')?>adminhtml/default/default/images/grid-cal.gif" alt="" class="v-middle" id="shipping_arrival_date_trig" title="Select Date" style="">
                            <input name="shipping_arrival_date" id="shipping_arrival_date" value="" onChange="shippingArrivalDateOnChange(this); return false;" title="date"  type="hidden">
                        </td>
                    </tr>
                </table>
            </td>
            <td width="15%">
                <table width="100%" cellspacing="0">
                    <tr>
                        <td><h3<?php if($this->getOrderLabels()) { echo ''; } else { echo ' style="display: none;"';} ?>><?php echo $this->__('UK Mail Labels:') ?></h3></td>
                        <td><input name="shipping_labels" type="text" id="order_labels" class="input-text required-entry" style="font-size: larger; width: 30px; height: 20px;<?php if($this->getOrderLabels()) { echo ''; } else { echo ' style="display: none;"';} ?>" value="<?php echo $this->getOrderLabels() ?>"/></td>
                    </tr>
                </table>
            </td>
    <td width="10%" style="padding: 5px;"><input type="button" onclick="holdForm.submitAction()"; style="border-top-width:0px;border-bottom-width:0px;border-left-width:0px;border-right-width:0px;border-top-left-radius:3px;border-top-right-radius:3px;border-bottom-right-radius:3px;border-bottom-left-radius:3px;border-color:#e04941;border-style:solid;background-color:#db3535;color:#ffffff;font-size:14px;font-weight:bold;font-style:normal;font-family:Arial;text-align:center;box-shadow:0 1px 2px rgba(0, 0, 0, 0.4);-o-box-shadow:0 1px 2px rgba(0, 0, 0, 0.4);-moz-box-shadow:0 1px 2px rgba(0, 0, 0, 0.4);-webkit-box-shadow:0 1px 2px rgba(0, 0, 0, 0.4);background-size:auto;background-repeat:repeat;background-position:center center;padding-top:6px;padding-right:10px;padding-bottom:6px;padding-left:10px;width:123px;height:54px;;" value="Put On Hold
(Go To Next)" id="el648319_891da0b2d5b96ce1ef86fa6693d07dfc"></td>
    <td width="15%" style="padding: 5px;"><input type="button" onclick="approveForm.submitAction()"; style="border-top-width:0px;border-bottom-width:0px;border-left-width:0px;border-right-width:0px;border-top-left-radius:3px;border-top-right-radius:3px;border-bottom-right-radius:3px;border-bottom-left-radius:3px;border-color:#dddddd;border-style:solid;background-color:#3498db;color:#FFF;font-size:14px;font-weight:bold;font-style:normal;font-family:Arial;text-align:center;box-shadow:0 1px 2px rgba(0, 0, 0, 0.4);-o-box-shadow:0 1px 2px rgba(0, 0, 0, 0.4);-moz-box-shadow:0 1px 2px rgba(0, 0, 0, 0.4);-webkit-box-shadow:0 1px 2px rgba(0, 0, 0, 0.4);background-size:auto;background-repeat:repeat;background-position:center center;padding-top:6px;padding-right:10px;padding-bottom:6px;padding-left:10px;width:213px;height:54px;;" value="Approve Order
Go To Next (<?php echo $this->escapeHtml($this->getCountNext()); ?>)" id="el402113_b96c656764a540818144280bd91b4c02"></td>
        </tr>
    </table>
</div>

<?php
$dayoff = $this->getDayOff();
?>

<script type="text/javascript">
    //<![CDATA[
    /*Calendar.setup({
     inputField: "shipping_arrival_date",
     ifFormat: "%m/%e/%Y",
     showsTime: false,
     button: "shipping_arrival_date_trig",
     align: "Bl",
     singleClick : true ,
     disableFunc: function(date) {
     return date.getMonth() === 1; // Sunday is 0, Monday is 1, and so on
     }
     });*/

    Calendar.prototype._init = function (firstDayOfWeek, date) {
        var today = new CalendarDateObject(),
            TY = today.getFullYear(),
            TM = today.getMonth(),
            TD = today.getDate();
        this.table.style.visibility = "hidden";
        var year = date.getFullYear();
        if (year < this.minYear) {
            year = this.minYear;
            date.setFullYear(year);
        } else if (year > this.maxYear) {
            year = this.maxYear;
            date.setFullYear(year);
        }
        this.firstDayOfWeek = firstDayOfWeek;
        this.date = new CalendarDateObject(date);
        var month = date.getMonth();
        var mday = date.getDate();
        var no_days = date.getMonthDays();
        /* Added By B.C. on date 18/02/2013 */
        var check_flag = false;
        /* END */

        // calendar voodoo for computing the first day that would actually be
        // displayed in the calendar, even if it's from the previous month.
        // WARNING: this is magic. ;-)
        date.setDate(1);
        var day1 = (date.getDay() - this.firstDayOfWeek) % 7;
        if (day1 < 0)
            day1 += 7;
        date.setDate(-day1);
        date.setDate(date.getDate() + 1);

        var row = this.tbody.firstChild;
        var MN = Calendar._SMN[month];
        var ar_days = this.ar_days = new Array();
        var weekend = Calendar._TT["WEEKEND"];
        var dates = this.multiple ? (this.datesCells = {}) : null;
        for (var i = 0; i < 6; ++i, row = row.nextSibling) {
            var cell = row.firstChild;
            if (this.weekNumbers) {
                cell.className = "day wn";
                cell.innerHTML = date.getWeekNumber();
                cell = cell.nextSibling;
            }
            row.className = "daysrow";
            var hasdays = false, iday, dpos = ar_days[i] = [];
            for (var j = 0; j < 7; ++j, cell = cell.nextSibling, date.setDate(iday + 1)) {
                iday = date.getDate();
                var wday = date.getDay();
                cell.className = "day";
                cell.pos = i << 4 | j;
                dpos[j] = cell;
                var current_month = (date.getMonth() == month);
                if (!current_month) {
                    if (this.showsOtherMonths) {
                        cell.className += " othermonth";
                        cell.otherMonth = true;
                    } else {
                        cell.className = "emptycell";
                        cell.innerHTML = "&nbsp;";
                        cell.disabled = true;
                        continue;
                    }
                } else {
                    cell.otherMonth = false;
                    hasdays = true;
                }
                cell.disabled = false;
                cell.innerHTML = this.getDateText ? this.getDateText(date, iday) : iday;
                if (dates)
                    dates[date.print("%Y%m%d")] = cell;
                if (this.getDateStatus) {
                    var status = this.getDateStatus(date, year, month, iday);
                    if (this.getDateToolTip) {
                        var toolTip = this.getDateToolTip(date, year, month, iday);
                        if (toolTip)
                            cell.title = toolTip;
                    }
                    if (status === true) {
                        cell.className += " disabled";
                        cell.disabled = true;
                    } else {
                        if (/disabled/i.test(status))
                            cell.disabled = true;
                        cell.className += " " + status;
                    }
                }
                if (!cell.disabled) {
                    cell.caldate = new CalendarDateObject(date);
                    cell.ttip = "_";
                    if (!this.multiple && current_month
                        && iday == mday && this.hiliteToday) {
                        cell.className += " selected";
                        this.currentDateEl = cell;
                    }
                    if (date.getFullYear() == TY &&
                        date.getMonth() == TM &&
                        iday == TD) {
                        cell.className += " today";
                        cell.ttip += Calendar._TT["PART_TODAY"];
                    }
                    if (weekend.indexOf(wday.toString()) != -1)
                        cell.className += cell.otherMonth ? " oweekend" : " weekend";
                    if (check_flag){
                        cell.className += " selected";
                        this.currentDateEl = cell;
                        check_flag=false;
                    }
                }else{
                    /* Added By B.C. on date 18/02/2013 */
                    if (!this.multiple && current_month
                        && iday == mday && this.hiliteToday) {
                        check_flag=true;
                    }

                    /* END */
                }
            }
            if (!(hasdays || this.showsOtherMonths))
                row.className = "emptyrow";
        }
        this.title.innerHTML = Calendar._MN[month] + ", " + year;
        this.onSetTime();
        this.table.style.visibility = "visible";
        this._initMultipleDates();
        // PROFILE
        // this.tooltips.innerHTML = "Generated in " + ((new CalendarDateObject()) - today) + " ms";
    };

    var dayoff = '<?php echo $dayoff; ?>';
    var test_flag = false;
    Calendar.setup({
        inputField: "shipping_arrival_date",
        ifFormat: "%Y-%mm-%ee %H:%M:%S",
        showsTime: true,
        button: "shipping_arrival_date_trig",
        align: "Bl",
        singleClick :true,
        onSelect :function()
        {
            //var y = calendar.date.getFullYear();
            currentTime1 = new Date();
            var m = parseInt(currentTime1.getMonth())+parseInt(1);
            var y=currentTime1.getFullYear();
            var d = currentTime1.getDate();



            currentTime = new Date(calendar.date.getTime());
            var d1=currentTime.getDate();
            var m1=parseInt(currentTime.getMonth())+parseInt(1);
            var y1=currentTime.getFullYear();
            var h1 = currentTime.getHours();
            var min1= currentTime.getMinutes();


            if (calendar.dateClicked)
            {
                if(d1 < d && m1==m && y1==y)
                {
                    alert("You can not select previous date.")
                    document.getElementById('shipping_arrival_date_display').value="";
                    document.getElementById('shipping_arrival_date').value="";
                    calendar.hide();
                }
                else
                {
                    document.getElementById('shipping_arrival_date_display').value=y1+"-"+m1+"-"+d1+" "+h1+":"+min1;
                    document.getElementById('shipping_arrival_date').value=y1+"-"+m1+"-"+d1+" "+h1+":"+min1;
                    calendar.hide();
                }
            }
            else
            {
                calendar.show();
            }
        },
        disableFunc : function(date)
        {
            var y = calendar.date.getFullYear();
            var m = calendar.date.getMonth();
            var d = calendar.date.getDate();

            var day_off_array = dayoff.split(",") ;

            currentTime = new Date();
            var d1=currentTime.getDate();
            var m1=currentTime.getMonth();
            var counter = 1;
            for (var i=0; i<day_off_array.length;i++){
                if (day_off_array[i]!=''){
                    var checkData = day_off_array[i].split('-');

                    if (date.getMonth()==(parseInt(checkData[1], 10) - 1)) {
                        if (date.getDate()==parseInt(checkData[0], 10)){
                            if (date.getDate()==currentTime.getDate()){
                                test_flag=true;
                            }
                            return true;
                        }
                    }
                }
            }

            if(m1 > m ) {
                return true;
            }
        }
    });

    function shippingArrivalDateOnChange(el)
    {
        var displayDate = $('shipping_arrival_date_display');
        var date = $('shipping_arrival_date').getValue();
        displayDate.setValue(date);
    }

    function resetArrivalDate()
    {
        //clear both fields

    }

    function updateLabels(el)
    {
        $$('.label-item').forEach(function(element, index, array) {
            var labels = 0;

            var selectElement = $(element.id + '_shippng_method');

            if (selectElement.value == 'ukmail') {
                labels = labels + parseInt(element.value, 10);
            }

            $('order_labels').value = labels;

            if (labels > 0) {
                labelShow();
            } else {
                labeHide();
            }
        })
    }

    function labelShow()
    {
        $('order_labels').show();
        $('order_labels').up(1).down('h3').show();
    }

    function labeHide()
    {
        $('order_labels').hide();
        $('order_labels').up(1).down('h3').hide();
    }

</script>

<?php endif; ?>