
<div class="block block-account">
    <div class="block-title">
        <?php echo $this->__('My Account'); ?>
    </div>
    <div class="block-content">
        <ul>
            <?php if(Mage::getSingleton( 'customer/session' )->isLoggedIn()) { ?>
                <li><a href="<?php echo $this->getUrl('')."customer/account/logout/"; ?>"><span><?php echo $this->__('Log Out') ?></span></a></li>
            <?php } ?>
            
            <?php $_links = $this->getLinks(); ?>
            <?php $_index = 1; ?>
            <?php
//            $_count = count($_links); /* Add or Remove Account Left Navigation Links Here -*/
                unset($_links['sagepaycards']); /* Sagepay Saved Cards */
                unset($_links['recurring_profiles']); /* Recurring Profiles */
                unset($_links['reviews']);  /* Reviews */
                unset($_links['tags']); /* My Tags */
                unset($_links['wishlist']); /* Wishlist */
                unset($_links['downloadable_products']); /* My Downloadable Products */
                unset($_links['OAuth Customer Tokens']); /* My Applications */
                unset($_links['billing_agreements']); /* Billing Agreements */
                unset($_links['aitloyalty']); /* Available Specials */
                unset($_links['raf']); /* Referred Friends */
                unset($_links['ProductReturn']); /* Product Returns */
            ?>
            <?php $_count = count($_links); ?>
            <?php foreach ($_links as $_link): ?>
                <?php $_last = ($_index++ >= $_count); ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="current<?php echo ($_last ? ' last' : '') ?>"><a><?php echo $_link->getLabel() ?></a></li>
                <?php else: ?>
                    <li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><span> <?php echo $_link->getLabel() ?></span></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div> <!--block-content-->
</div> <!--block block-account-->
