<?php 
/* Newsletter subscribe */
?>

<div class="newsletter">
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail1">
     <div>
      <h4><span><?php echo $this->__('Receive our ') ?></span><?php echo $this->__('newsletter') ?></h4>
      <input type="text" name="email" id="newsletter1" class="input-text" placeholder="Enter your email address" required />
      <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="subscribe"><span><?php echo $this->__('Subscribe') ?></span></button>
     </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail1');
    //]]>
    </script>
</div> <!--newsletter-->
