<?php 
/* Top shopping Cart  */ 
?>
<?php /*
<div class="top-cart-contain">
  <div class="mini-cart">
  <div class="basket dropdown-toggle" data-hover="dropdown" data-toggle="dropdown"> 

     
      <a href="<?php echo $this->getUrl('checkout/cart') ?>"><i class="icon-cart"></i> <div class="cart-box"><span class="title"><?php echo $this->__('my Cart');?></span><span id="cart-total"> <?php if(Mage::helper('checkout/cart')->getSummaryCount() > 1) { echo Mage::helper('checkout/cart')->getSummaryCount() . $this->__(' items'); } elseif(Mage::helper('checkout/cart')->getSummaryCount() == 1) { echo "1 item"; }  else {echo "0 item"; } ?> </span></div></a></div>
      <div>
      <div class="top-cart-content  arrow_box">
         <?php $_items = $this->getRecentItems() ?>
         <?php if(count($_items)): ?>   
           <div class="block-subtitle"><?php echo $this->__('Recently added item(s)') ?></div> 
            <ul id="cart-sidebar" class="mini-products-list">
               <?php foreach($_items as $_item): ?>
                   <?php echo $this->getItemHtml($_item) ?>
               <?php endforeach; ?>               
            </ul>                              
            <div class="top-subtotal">
                 <?php echo $this->__('Subtotal:');?>                   
                 <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>            
            </div> <!--top-subtotal-->
            <div class="actions">
              <button type="button" class="view-cart" onclick="window.location='<?php echo $this->getUrl('checkout/cart') ?>';" title="<?php echo $this->__('View Cart') ?>" ><span><?php echo $this->__('View Cart') ?></span></button>                 
              <button type="button" title="<?php echo $this->__('Checkout') ?>" class="btn-checkout" onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';"><span><?php echo $this->__('Checkout') ?></span></button>                         
            </div>  <!--actions-->
           <?php else: ?>               
                <p class="a-center noitem"><?php echo $this->__('You have no items in your shopping cart.') ?></p>               
            <?php endif ?>
      </div> <!--top-cart-content-->
  </div>
  </div> <!--mini-cart-->
</div> <!--top-cart-contain-->
*/ ?>

<ul class="header-circles">

  <li>
    <a href="<?php echo $this->getUrl('contacts')?>">
      <div class="header-circles-circle">
        <span class="whf-icon whf-icon-envelope"></span>
      </div>
      <span class="header-circles-title">Contact us</span>
    </a>
  </li>

  <li>
    <a href="<?php echo $this->getUrl('customer/account')?>">
      <div class="header-circles-circle">
        <span class="whf-icon whf-icon-person"></span>
      </div>
      <span class="header-circles-title"><?php echo $this->__('Account') ?></span>
    </a>
  </li>

  <?php if(Mage::getSingleton( 'customer/session' )->isLoggedIn()) { ?>
    <li>
      <a href="<?php echo $this->getUrl('')."customer/account/logout/"; ?>">
        <div class="header-circles-circle">
          <span class="whf-icon whf-icon-person"></span>
        </div>
        <span class="header-circles-title"><?php echo $this->__('Log Out') ?></span>
      </a>
    </li>
  <?php } ?>

  <li class="jsHeaderCirclesCart">
    <a href="<?php echo $this->getUrl('checkout/cart') ?>">
      <div class="header-circles-circle">
        <span class="whf-icon whf-icon-trolley"></span>

        <?php if (Mage::helper('checkout/cart')->getSummaryCount() > 1): ?>
          <span class="header-circles-count"><?php echo Mage::helper('checkout/cart')->getSummaryCount(); ?></span>
        <?php endif; ?>
      </div>
      <span class="header-circles-title">Basket</span>
    </a>

    <div class="top-cart-content arrow_box jsTopCartContent">
    <?php $_items = $this->getRecentItems() ?>
    <?php if(count($_items)): ?>   
    <div class="block-subtitle"><?php echo $this->__('Recently added item(s)') ?></div> 
    <ul id="cart-sidebar" class="mini-products-list">
    <?php foreach($_items as $_item): ?>
    <?php echo $this->getItemHtml($_item) ?>
    <?php endforeach; ?>               
    </ul>                              
    <div class="top-subtotal">
    <?php echo $this->__('Subtotal:');?>                   
    <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>            
    </div> <!--top-subtotal-->
    <div class="actions">
    <button type="button" class="view-cart" onclick="window.location='<?php echo $this->getUrl('checkout/cart') ?>';" title="<?php echo $this->__('View Basket') ?>" ><span><?php echo $this->__('View Basket') ?></span></button>
    <button type="button" title="<?php echo $this->__('Checkout') ?>" class="btn-checkout" onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';"><span><?php echo $this->__('Checkout') ?></span></button>                         
    </div>  <!--actions-->
    <?php else: ?>               
    <p class="a-center noitem"><?php echo $this->__('You have no items in your shopping basket.') ?></p>
    <?php endif ?>
    </div> <!--top-cart-content-->
  </li>

</ul>
