<?php
/**
 * @package Vine-House-Farm.
 * @author: A.A.Treitjak <a.treitjak@gmail.com>
 * @copyright: 2012 - 2015 BelVG.com
 */

class Vinehousefarm_Productvideo_Model_Video extends Mage_Core_Model_Abstract
{
    public function _construct()
    {
        parent::_construct();
        $this->_init('productvideo/video');
    }

    protected function _beforeSave()
    {
        if ($this->hasData('in_products') && !is_array($this->getInProducts())) {
            $products = array();
            parse_str($this->getInProducts(), $products);
            $this->setInProducts($products);
        }

        return parent::_beforeSave(); // TODO: Change the autogenerated stub
    }

    protected function _afterSave()
    {
        if ($this->getInProducts()) {

            /**
             * @var $delete Vinehousefarm_Productvideo_Model_Resource_Product_Collection
             */
            $delete = Mage::getModel('productvideo/product')->getCollection()
                ->addFieldToFilter('video_id', $this->getId());

            $delete->walk('delete');

            /**
             * @var $create Vinehousefarm_Productvideo_Model_Resource_Product_Collection
             */

            $create = Mage::getModel('productvideo/product')->getCollection();

            foreach ($this->getInProducts() as $productId) {

                /**
                 * @var $linkModel Vinehousefarm_Productvideo_Model_Product
                 */

                $linkModel = Mage::getModel('productvideo/product');
                $linkModel->isObjectNew(true);
                $linkModel->setVideoId($this->getId());
                $linkModel->setProductId($productId);
                $linkModel->save();
            }
        }

        return parent::_afterSave(); // TODO: Change the autogenerated stub
    }

    protected function _afterDelete()
    {
        if ($this->getInProducts()) {

            /**
             * @var $delete Vinehousefarm_Productvideo_Model_Resource_Product_Collection
             */
            $delete = Mage::getModel('productvideo/product')->getCollection()
                ->addFieldToFilter('video_id', $this->getId());

            $delete->walk('delete');
        }

        return parent::_afterDelete(); // TODO: Change the autogenerated stub
    }

    protected function _afterLoad()
    {
        if (!$this->getInProducts()) {

            /**
             * @var $products Vinehousefarm_Productvideo_Model_Resource_Product_Collection
             */
            $products = Mage::getModel('productvideo/product')->getCollection()
                ->addFieldToFilter('video_id', $this->getId());

            $result = array();

            foreach ($products as $product) {
                $result[] = $product->getProductId();
            }

            if ($result) {
                $this->setInProducts($result);
            } else {
                $this->setInProducts('');
            }
        }

        return parent::_afterLoad(); // TODO: Change the autogenerated stub
    }
}