<?php
/**
 * @package Vine-House-Farm.
 * @author: A.A.Treitjak <a.treitjak@gmail.com>
 * @copyright: 2012 - 2015 BelVG.com
 */
?>
<?php if(count($this->getItemCollection()->getItems())): ?>
<div class="upsell-slider onpageslider">
    <div class="new_title center">
        <h2><?php echo $this->__('Feed to Food') ?></h2>
    </div>
    <a id="products_slider_prev" class="jcarousel-prev-horizontal2" href="#"></a>
    <a id="products_slider_next" class="jcarousel-next-horizontal2" href="#"></a>
    <div class="jcarousel-skin-tango4">
        <div class="jcarousel-container jcarousel-container-horizontal" style="position: relative; display: block;">
            <div class="jcarousel-clip jcarousel-clip-horizontal" style="overflow: hidden; position: relative;">
                <ul id="featured_products_slider" class="products-grid jcarousel-list jcarousel-list-horizontal" style="overflow: hidden; position: relative; top: 0px; margin: 0px; padding: 0px; left: 0px; width: 295px;">
                    <?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
                    <?php $this->resetItemsIterator() ?>
                    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
                        <?php for($_j=0;$_j<14;$_j++): ?>
                        <?php if($_link=$this->getIterableItem()): ?>
                    <li class="item first jcarousel-item jcarousel-item-horizontal jcarousel-item-1 jcarousel-item-1-horizontal" style="float: left; list-style: none;">
                        <div class="item-inner">
                            <div class="product-wrapper">
                                <div class="thumb-wrapper">
                                    <a class="thumb flip" title="<?php echo $this->escapeHtml($_link->getName()) ?>" href="<?php echo $_link->getProductUrl() ?>">
                                        <span class="face">
                                            <img alt="<?php echo $this->escapeHtml($_link->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(125) ?>" /></span>
                                        <span class="face back">
                                            <img title="<?php echo $this->escapeHtml($_link->getName()) ?>" alt="<?php echo $this->escapeHtml($_link->getName()) ?>" src="{{store url=" /> </span>
                                    </a>
                                </div>
                                <!--thumb-wrapper-->
                                <div class="actions">
                                    <span class="add-to-links">
                                        <a class="link-wishlist" title="Add to Wishlist" href="<?php echo Mage::helper('wishlist')->getAddUrl($_link); ?>"><span>Add to Wishlist</span></a>
                                        <a class="link-compare" title="Add to Compare" href="<?php echo Mage::helper('catalog/product_compare')->getAddUrl($_link); ?>"><span>Add to Compare</span></a> </span> <!--add-to-links-->
                                </div>
                                <!--actions-->
                            </div>
                            <!--product-wrapper-->
                            <div class="item-info">
                                <div class="info-inner">
                                    <div class="item-title"><a title="<?php echo $this->escapeHtml($_link->getName()) ?>" href="<?php echo $_link->getProductUrl() ?>"><?php echo $this->escapeHtml($_link->getName()) ?></a></div>
                                    <!--item-title-->
                                    <div class="item-content">
                                        <div class="ratings">&nbsp;</div>
                                        <?php echo $this->getPriceHtml($_link, true) ?>
                                    </div>
                                    <!--item-content--></div>
                                <!--info-inner-->
                                <div class="actions"><button class="button btn-cart" title="Add to Cart" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($_link); ?>')" type="button"><span>Add to Cart</span></button></div>
                                <!--actions--></div>
                            <!--item-info--></div>
                        <!--item-inner--></li>
                            <?php endif; ?>
                        <?php endfor; ?>
                    <?php endfor; ?>
                </ul>
            </div>
        </div>

            <script type="text/javascript">// <![CDATA[
                jQuery(document).ready(function($) {

                    function mycarousel_initCallback(carousel) {

                        $('#products_slider_next').bind('click', function() {
                            carousel.next();
                            return false;
                        });
                        $('#products_slider_prev').bind('click', function() {
                            carousel.prev();
                            return false;
                        });
                    };

                    $('#featured_products_slider').jcarousel({
                        scroll: 1,
                        initCallback: mycarousel_initCallback,
                        buttonNextHTML: null,
                        buttonPrevHTML: null
                    });
                });
                // ]]></script>
            <div id="mgkquickview">
                <div id="magikloading" style="display: none; text-align: center; margin-top: 400px;"><img alt="loading" src="{{store url=""}}/skin/frontend/rwd/lamby/images/mgkloading.gif" /></div>
            </div>
            <script type="text/javascript">// <![CDATA[
                function callQuickView(qurl) {
                    jQuery('#mgkquickview').show();
                    jQuery('#magikloading').show();
                    jQuery.get(qurl, function(data) {
                        jQuery.fancybox(data);
                        jQuery('#magikloading').hide();
                        jQuery('#mgkquickview').hide();
                    });
                }

                // ]]></script>

    </div>
</div>
<?php endif ?>