<?php
/**
 * @package Vine-House-Farm.
 * @author: A.A.Treitjak <a.treitjak@gmail.com>
 * @copyright: 2012 - 2015 BelVG.com
 */
?>

    <h2><?php echo $this->helper('birdlibrary')->__('Video'); ?></h2>
    <div class="whf-video-player-container">
        <div class="whf-video-player">
            <iframe src="https://www.youtube.com/embed/<?php echo $this->getBird()->getVideoFile() ?>" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>

