<?php
/**
 * @package Vine-House-Farm.
 * @author A.Treitjak <a.treitjak@gmail.com>
 * @copyright 2012 - 2016
 */

class Vinehousefarm_Ukmail_Model_Label extends Mage_Core_Model_Abstract
{
    public function _construct()
    {
        parent::_construct();
        $this->_init('ukmail/label');
    }

    protected function _afterDelete()
    {
        Mage::helper('ukmail/label')->remove($this);

        return parent::_afterDelete(); // TODO: Change the autogenerated stub
    }
}