<?php $config = Mage::getStoreConfig('lambysettings/lambysettings_appearance'); ?>

<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=no" />
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<?php /*<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />*/ ?>
<?php /*<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />*/ ?>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,300,700,800,400,600' rel='stylesheet' type='text/css'>
<?php /*<link href='//fonts.googleapis.com/css?family=<?php echo str_replace(' ', '+', $config['font']); ?>:200,300,400,500,600,700,800' rel='stylesheet' type='text/css'> */ ?>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

<?php /*<script type="text/javascript">
  jQuery(window).scroll(function() {
   if (jQuery(this).scrollTop() > 1){  
       jQuery('nav').addClass("sticky");
   }
   else{
       jQuery('nav').removeClass("sticky");
   }
});
</script>*/ ?>

<script type="text/javascript">
        jQuery(document).ready(function(){
            jQuery('#rev_slider_4').show().revolution({
                dottedOverlay: 'none',
                delay: 5000,
                startwidth: 770,
                startheight: 460,

                hideThumbs: 200,
                thumbWidth: 200,
                thumbHeight: 50,
                thumbAmount: 2,

                navigationType: 'thumb',
                navigationArrows: 'solo',
                navigationStyle: 'round',

                touchenabled: 'on',
                onHoverStop: 'on',
                
                swipe_velocity: 0.7,
                swipe_min_touches: 1,
                swipe_max_touches: 1,
                drag_block_vertical: false,
            
                spinner: 'spinner0',
                keyboardNavigation: 'off',

                navigationHAlign: 'center',
                navigationVAlign: 'bottom',
                navigationHOffset: 0,
                navigationVOffset: 20,

                soloArrowLeftHalign: 'left',
                soloArrowLeftValign: 'center',
                soloArrowLeftHOffset: 20,
                soloArrowLeftVOffset: 0,

                soloArrowRightHalign: 'right',
                soloArrowRightValign: 'center',
                soloArrowRightHOffset: 20,
                soloArrowRightVOffset: 0,

                shadow: 0,
                fullWidth: 'on',
                fullScreen: 'off',

                stopLoop: 'off',
                stopAfterLoops: -1,
                stopAtSlide: -1,

                shuffle: 'off',

                autoHeight: 'off',
                forceFullWidth: 'on',
                fullScreenAlignForce: 'off',
                minFullScreenHeight: 0,
                hideNavDelayOnMobile: 1500,
            
                hideThumbsOnMobile: 'off',
                hideBulletsOnMobile: 'off',
                hideArrowsOnMobile: 'off',
                hideThumbsUnderResolution: 0,

                hideSliderAtLimit: 0,
                hideCaptionAtLimit: 0,
                hideAllCaptionAtLilmit: 0,
                startWithSlide: 0,
                fullScreenOffsetContainer: ''
            });
        });
        </script>



<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<script type="text/javascript">
var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
var SKIN_URL = '<?php echo $this->helper('core/js')->getJsSkinUrl('') ?>';
</script>
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>

<script type="text/javascript">
    jQuery.noConflict();

    jQuery(document).ready(function(){
        homeBxslider = jQuery('.home-slider .bxslider').bxSlider({
            controls: false,
            onSlideBefore: function(slideElement, oldIndex, newIndex) {
                jQuery('.home-slider .bx-wrapper .bx-viewport .bxslider li').removeClass('active');
            },
            onSlideAfter: function(slideElement, oldIndex, newIndex) {
                slideElement.addClass('active');
            },
            onSliderLoad: function() {
                jQuery('.home-slider .bx-wrapper .bx-viewport .bxslider li').not('.bx-clone').first().addClass('active');
            }
        });

        jQuery('.home-slider-nav.prev').click(function(e){
            e.preventDefault();
            homeBxslider.goToPrevSlide();
        });

        jQuery('.home-slider-nav.next').click(function(e){
            e.preventDefault();
            homeBxslider.goToNextSlide();
        });

        // start bird gallery bxslider
        birdsBxslider = jQuery('.whf-bird-gallery .bxslider').bxSlider({
            controls: false,
            pager: false
        });

        jQuery('.whf-bird-gallery .jcarousel-prev-horizontal2').click(function(e){
            e.preventDefault();
            birdsBxslider.goToPrevSlide();
        });

        jQuery('.whf-bird-gallery .jcarousel-next-horizontal2').click(function(e){
            e.preventDefault();
            birdsBxslider.goToNextSlide();
        });
        // end bird gallery bxslider

        // start offer blocks hovers
        jQuery('.whf-button[data-hovercolor]').each(function() {
            var color = jQuery(this).attr('data-hovercolor');

            jQuery(this).hover(function() {
                jQuery(this).css('color', color);
            }, function() {
                jQuery(this).css('color', '');
            });
        });

        jQuery('.whf-button[data-hoverbackground]').each(function() {
            var hoverbackground = jQuery(this).attr('data-hoverbackground');

            jQuery(this).hover(function() {
                jQuery(this).css('background-color', hoverbackground);
                jQuery(this).css('border-color', hoverbackground);
            }, function() {
                jQuery(this).css('background-color', '');
                jQuery(this).css('border-color', '');
            });
        });
        // end offer blocks hovers

        jQuery('.home-video .whf-icon-play').click(function(e) {
            e.preventDefault();

            var container = jQuery(this).closest('.home-video');

            container.find('.home-video-player-iframe').addClass('active');
        });
    });
</script>

<link rel="apple-touch-icon" sizes="57x57" href="<?php echo $this->getSkinUrl('images/vinehousefarm/favicons/apple-touch-icon-57x57.png'); ?>">
<link rel="apple-touch-icon" sizes="60x60" href="<?php echo $this->getSkinUrl('images/vinehousefarm/favicons/apple-touch-icon-60x60.png'); ?>">
<link rel="apple-touch-icon" sizes="72x72" href="<?php echo $this->getSkinUrl('images/vinehousefarm/favicons/apple-touch-icon-72x72.png'); ?>">
<link rel="apple-touch-icon" sizes="76x76" href="<?php echo $this->getSkinUrl('images/vinehousefarm/favicons/apple-touch-icon-76x76.png'); ?>">
<link rel="apple-touch-icon" sizes="114x114" href="<?php echo $this->getSkinUrl('images/vinehousefarm/favicons/apple-touch-icon-114x114.png'); ?>">
<link rel="apple-touch-icon" sizes="120x120" href="<?php echo $this->getSkinUrl('images/vinehousefarm/favicons/apple-touch-icon-120x120.png'); ?>">
<link rel="apple-touch-icon" sizes="144x144" href="<?php echo $this->getSkinUrl('images/vinehousefarm/favicons/apple-touch-icon-144x144.png'); ?>">
<link rel="apple-touch-icon" sizes="152x152" href="<?php echo $this->getSkinUrl('images/vinehousefarm/favicons/apple-touch-icon-152x152.png'); ?>">
<link rel="apple-touch-icon" sizes="180x180" href="<?php echo $this->getSkinUrl('images/vinehousefarm/favicons/apple-touch-icon-180x180.png'); ?>">
<link rel="icon" type="image/png" href="<?php echo $this->getSkinUrl('images/vinehousefarm/favicons/favicon-32x32.png'); ?>" sizes="32x32">
<link rel="icon" type="image/png" href="<?php echo $this->getSkinUrl('images/vinehousefarm/favicons/android-chrome-192x192.png'); ?>" sizes="192x192">
<link rel="icon" type="image/png" href="<?php echo $this->getSkinUrl('images/vinehousefarm/favicons/favicon-96x96.png'); ?>" sizes="96x96">
<link rel="icon" type="image/png" href="<?php echo $this->getSkinUrl('images/vinehousefarm/favicons/favicon-16x16.png'); ?>" sizes="16x16">
<link rel="manifest" href="<?php echo $this->getSkinUrl('images/vinehousefarm/favicons/manifest.json'); ?>">
<meta name="msapplication-TileColor" content="#212c60">
<meta name="msapplication-TileImage" content="<?php echo $this->getSkinUrl('images/vinehousefarm/favicons/mstile-144x144.png'); ?>">
<meta name="theme-color" content="#ffffff">
